import io
import base64
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table,
    TableStyle, HRFlowable
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT


def generate_pdf_report(analysis_result, session_id=None):
    """Generate a professional PDF report from analysis results."""
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=20*mm,
        leftMargin=20*mm,
        topMargin=20*mm,
        bottomMargin=20*mm
    )

    styles = getSampleStyleSheet()
    story = []

    # Colors
    NAVY = colors.HexColor("#0a1628")
    CYAN = colors.HexColor("#06b6d4")
    LIGHT_BLUE = colors.HexColor("#e0f2fe")
    GRAY = colors.HexColor("#64748b")
    WHITE = colors.white
    GREEN = colors.HexColor("#22c55e")
    YELLOW = colors.HexColor("#eab308")
    ORANGE = colors.HexColor("#f97316")
    RED = colors.HexColor("#ef4444")

    def status_color(status):
        mapping = {
            "Optimal": GREEN,
            "Normal": colors.HexColor("#84cc16"),
            "Mild Variation": YELLOW,
            "Moderate Variation": ORANGE,
            "Elevated Concern": RED,
            "Thermally Stable": GREEN,
            "Mild Instability": YELLOW,
            "Moderate Instability": ORANGE,
            "High Instability": RED,
            "Stable": GREEN,
            "Unstable": RED,
        }
        return mapping.get(status, GRAY)

    # Title style
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Title'],
        fontSize=24,
        textColor=NAVY,
        spaceAfter=4,
        fontName='Helvetica-Bold',
        alignment=TA_CENTER
    )

    subtitle_style = ParagraphStyle(
        'SubtitleStyle',
        parent=styles['Normal'],
        fontSize=11,
        textColor=CYAN,
        spaceAfter=2,
        fontName='Helvetica',
        alignment=TA_CENTER
    )

    heading_style = ParagraphStyle(
        'HeadingStyle',
        parent=styles['Heading1'],
        fontSize=13,
        textColor=NAVY,
        spaceBefore=12,
        spaceAfter=6,
        fontName='Helvetica-Bold'
    )

    normal_style = ParagraphStyle(
        'NormalStyle',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.HexColor("#334155"),
        spaceAfter=4,
        fontName='Helvetica'
    )

    disclaimer_style = ParagraphStyle(
        'DisclaimerStyle',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.HexColor("#dc2626"),
        spaceAfter=4,
        fontName='Helvetica-Oblique',
        alignment=TA_CENTER
    )

    small_style = ParagraphStyle(
        'SmallStyle',
        parent=styles['Normal'],
        fontSize=8,
        textColor=GRAY,
        fontName='Helvetica'
    )

    # ── Header ──
    story.append(Paragraph("ThermalRiskAI", title_style))
    story.append(Paragraph("Thermal Perfusion Stability Analysis Report", subtitle_style))
    story.append(Spacer(1, 4*mm))
    story.append(HRFlowable(width="100%", thickness=2, color=CYAN))
    story.append(Spacer(1, 3*mm))

    # Session info
    now = datetime.now().strftime("%B %d, %Y at %H:%M UTC")
    sid = session_id or datetime.now().strftime("TRA-%Y%m%d-%H%M%S")
    region = analysis_result.get("region_type", "feet").capitalize()

    info_data = [
        ["Session ID", sid, "Date", now],
        ["Model", "EfficientNet-B0 + UMAP PSE", "", ""],
    ]

    info_table = Table(info_data, colWidths=[35*mm, 65*mm, 25*mm, 55*mm])
    info_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
        ('TEXTCOLOR', (0, 0), (0, -1), GRAY),
        ('TEXTCOLOR', (2, 0), (2, -1), GRAY),
        ('TEXTCOLOR', (1, 0), (1, -1), NAVY),
        ('TEXTCOLOR', (3, 0), (3, -1), NAVY),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (2, 0), (2, -1), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 4*mm))

    # ── Disclaimer ──
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#fca5a5")))
    story.append(Spacer(1, 2*mm))
    story.append(Paragraph(
        "⚠️ MEDICAL DISCLAIMER: This report is generated by an AI-powered research tool for "
        "computational thermal pattern analysis only. All findings, scores, organ status indicators, "
        "and health assessments are NON-DIAGNOSTIC computational research indicators. "
        "They do not constitute medical advice, diagnosis, or treatment recommendations. "
        "Always consult a qualified healthcare professional for medical decisions.",
        disclaimer_style
    ))
    story.append(Spacer(1, 2*mm))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#fca5a5")))
    story.append(Spacer(1, 4*mm))

    # ── Core Metrics ──
    story.append(Paragraph("Core Analysis Metrics", heading_style))

    ndvii = analysis_result.get("ndvii", 0)
    stability = analysis_result.get("stability_label", "N/A")
    stability_score = analysis_result.get("stability_score", 0)
    predicted_class = analysis_result.get("predicted_class", "N/A")
    confidence = analysis_result.get("confidence", 0)
    drift = analysis_result.get("drift_indicator", "N/A")
    instability = analysis_result.get("instability_index", 0)

    metrics_data = [
        ["Metric", "Value", "Status"],
        ["NDVII Score", f"{ndvii:.4f}", stability],
        ["Stability Score", f"{stability_score:.1f} / 100", "—"],
        ["Predicted Class", predicted_class, f"{confidence:.1f}% confidence"],
        ["Drift Indicator", drift, "—"],
        ["Instability Index", f"{instability:.2f}", "—"],
        ["Mean Surface Temp", f"{analysis_result.get('stats', {}).get('mean_temp', 0):.1f}°C", "—"],
        ["Bilateral Differential", f"{analysis_result.get('stats', {}).get('bilateral_differential', 0):.2f}°C", "—"],
        ["Gradient Zones", str(analysis_result.get('stats', {}).get('gradient_zones', 0)), "—"],
    ]

    metrics_table = Table(metrics_data, colWidths=[65*mm, 55*mm, 60*mm])
    metrics_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), NAVY),
        ('TEXTCOLOR', (0, 0), (-1, 0), WHITE),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('FONTNAME', (0, 1), (0, -1), 'Helvetica-Bold'),
        ('TEXTCOLOR', (0, 1), (0, -1), NAVY),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, LIGHT_BLUE]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]))

    # Color status column
    for row_idx, row in enumerate(metrics_data[1:], 1):
        status_val = row[2]
        col = status_color(status_val)
        if col != GRAY:
            metrics_table.setStyle(TableStyle([
                ('TEXTCOLOR', (2, row_idx), (2, row_idx), col),
                ('FONTNAME', (2, row_idx), (2, row_idx), 'Helvetica-Bold'),
            ]))

    story.append(metrics_table)
    story.append(Spacer(1, 6*mm))

    # ── Organ Zone Analysis ──
    organ_data = analysis_result.get("organ_mapping", {})
    if organ_data:
        story.append(Paragraph("Organ Zone Thermal Analysis", heading_style))
        story.append(Paragraph(
            f"Region: {organ_data.get('region_type', 'feet').capitalize()} | "
            f"Overall Health Score: {organ_data.get('overall_health_score', 0)}/100",
            normal_style
        ))
        story.append(Spacer(1, 3*mm))

        organs = organ_data.get("organs", [])
        organ_table_data = [["System", "Description", "Zone", "Status", "Perfusion", "Thermal Δ"]]

        for org in organs:
            organ_table_data.append([
                org["system"],
                org["description"],
                org["zone"],
                org["status"],
                f"{org['perfusion_level']}%",
                f"{org['thermal_variation']:+.2f}°C"
            ])

        organ_table = Table(
            organ_table_data,
            colWidths=[28*mm, 40*mm, 40*mm, 28*mm, 18*mm, 18*mm]
        )
        organ_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), NAVY),
            ('TEXTCOLOR', (0, 0), (-1, 0), WHITE),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, LIGHT_BLUE]),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ('ALIGN', (3, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ('WORDWRAP', (0, 0), (-1, -1), True),
        ]))

        for row_idx, org in enumerate(organs, 1):
            col = status_color(org["status"])
            organ_table.setStyle(TableStyle([
                ('TEXTCOLOR', (3, row_idx), (3, row_idx), col),
                ('FONTNAME', (3, row_idx), (3, row_idx), 'Helvetica-Bold'),
            ]))

        story.append(organ_table)
        story.append(Spacer(1, 6*mm))

        # Systems summary
        story.append(Paragraph("System-Level Summary", heading_style))
        summary = organ_data.get("systems_summary", [])
        if summary:
            summary_data = [["Body System", "Status", "Avg Concern Level"]]
            for s in summary:
                summary_data.append([
                    s["system"],
                    s["status"],
                    f"{s['average_concern']:.2f} / 4.0"
                ])

            summary_table = Table(summary_data, colWidths=[60*mm, 60*mm, 60*mm])
            summary_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), NAVY),
                ('TEXTCOLOR', (0, 0), (-1, 0), WHITE),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, LIGHT_BLUE]),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('TOPPADDING', (0, 0), (-1, -1), 5),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ]))

            for row_idx, s in enumerate(summary, 1):
                col = status_color(s["status"])
                summary_table.setStyle(TableStyle([
                    ('TEXTCOLOR', (1, row_idx), (1, row_idx), col),
                    ('FONTNAME', (1, row_idx), (1, row_idx), 'Helvetica-Bold'),
                ]))

            story.append(summary_table)

    # ── Footer ──
    story.append(Spacer(1, 8*mm))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cbd5e1")))
    story.append(Spacer(1, 3*mm))
    story.append(Paragraph(
        "ThermalRiskAI — AI-Powered Thermal Perfusion Research Platform | "
        "Non-Diagnostic Research Tool | Not for Clinical Use",
        ParagraphStyle('footer', parent=styles['Normal'], fontSize=7,
                      textColor=GRAY, alignment=TA_CENTER)
    ))

    doc.build(story)
    buffer.seek(0)
    return base64.b64encode(buffer.read()).decode("utf-8")